version: "3.6"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "8080:8080"
    container_name:
      app
    volumes:
      - .:/code
  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./databaseconfig:/docker-entrypoint-initdb.d/:ro
    container_name:
      db